version: "2"
services:
  application1:
    image: alpha-java-task2
    expose:
    - "8081"
    ports:
    - "8081:8081"
    depends_on:
      - postgresql
  postgresql:
    restart: always
    image: postgres:11
    container_name: postgresql
    hostname: postgresql
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=271828
    - POSTGRES_DB=test2