server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:29092

  datasource:
    url: jdbc:postgresql://localhost/test2?stringtype=unspecified
    username: postgres
    password: 271828

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 0
    check-location: true
